centos mirror script. update rvm-installer

diff --git a/env_ruby/rvm-installer b/env_ruby/rvm-installer
--- a/env_ruby/rvm-installer
+++ b/env_ruby/rvm-installer
@@ -1,18 +1,39 @@
 #!/usr/bin/env bash
 
+# echo "65536 * 3 + 256 * 2 + 25" | bc
+if [[ -n "${BASH_VERSION:-}" ]] &&
+  (( 65536 * ${BASH_VERSINFO[0]} + 256 * ${BASH_VERSINFO[1]} + ${BASH_VERSINFO[2]} < 197145 ))
+then
+  echo "BASH 3.2.25 required (you have $BASH_VERSION)"
+  exit 1
+fi
+
 shopt -s extglob
 PS4="+ \${BASH_SOURCE##\${rvm_path:-}} : \${FUNCNAME[0]:+\${FUNCNAME[0]}()}  \${LINENO} > "
 export PS4
 set -o errtrace
 set -o errexit
 
-log()  { printf "$*\n" ; return $? ;  }
+log()  { printf "%b\n" "$*" ; return $? ;  }
 
 fail() { log "\nERROR: $*\n" ; exit 1 ; }
 
+if [[ -z "${rvm_tar_command:-}" ]] && builtin command -v gtar >/dev/null
+then
+  rvm_tar_command=gtar
+else
+  rvm_tar_command=tar
+fi
+if [[ ! " ${rvm_tar_options:-} " =~ " --no-same-owner "  ]] && \
+  $rvm_tar_command --help | GREP_OPTIONS="" \grep -- --no-same-owner >/dev/null
+then
+  rvm_tar_options="${rvm_tar_options:-} --no-same-owner"
+  rvm_tar_options="${rvm_tar_options## }"
+fi
+
 usage()
 {
-  printf "
+  printf "%b" "
 
 Usage
 
@@ -20,149 +41,133 @@ Usage
 
 Options
 
-  --branch <name>               - Install RVM head, from named branch
-  --version <head|latest|x.y.z> - Install RVM version [head|latest|x.y.z]
-  --trace                       - used to debug the installer script
+  [[--]version] <latest|latest-x|latest-x.y|x.y.z> - Install RVM version
+  [--]branch    <name> - Install RVM head, from named branch
+  --trace              - used to debug the installer script
 
 Actions
 
-  help - Display CLI help (this output)
+  master - Install RVM master branch from wayneeseguin rvm repo (Default).
+  stable - Install RVM stable branch from wayneeseguin rvm repo.
+  help   - Display CLI help (this output)
+
+Branches:
+
+  branch <branch>
+  branch /<branch>
+  branch <repo>/
+  branch <repo>/<branch>
+
+  Defaults:
+
+    branch: master
+    repo:   wayneeseguin
 
 "
 }
 
+#Searches for highest available version for the given pattern
+# fetch_version 1.10. -> 1.10.3
+# fetch_version 1. -> 1.11.0
+# fetch_version "" -> 2.0.1
 fetch_version()
 {
-  version=$(curl -s -B "${rvm_releases_url}/latest-version.txt" 2>/dev/null)
-}
-
-fetch_md5()
-{
-  md5=$(curl -s -B "${rvm_releases_url}/rvm-${version}.tar.gz.md5" 2>/dev/null)
-}
-
-md5_match()
-{
-  local archive="$1"
-
-  case "$(uname)" in
-    Darwin|FreeBSD)
-      archive_md5="$(/sbin/md5 -q "${archive}")"
-      ;;
-
-    OpenBSD)
-      archive_md5="$(/bin/md5 -q "${archive}")"
-      ;;
-
-    Linux|*)
-      archive_md5="$(md5sum "${archive}")"
-      archive_md5="${archive_md5%% *}"
-      ;;
-  esac
-
-  if [[ "$archive_md5" == "$md5" ]]
-  then
-    return 0
-  else
-    return 1
-  fi
+  curl -s https://api.github.com/repos/wayneeseguin/rvm/tags |
+    sed -n '/"name": / {s/^.*".*": "\(.*\)".*$/\1/; p;}' |
+    sort -t. -k 1,1n -k 2,2n -k 3,3n -k 4,4n -k 5,5n |
+    GREP_OPTIONS="" \grep "^${1:-}" | tail -n 1
 }
 
 install_release()
 {
-  local archive url
-
-  archive="${rvm_archives_path}/rvm-${version}.tar.gz"
-  url="${rvm_releases_url}/rvm-${version}.tar.gz"
-
-  fetch_md5
-
-  if [[ -s "${archive}" && -n "${md5}" ]] && ! md5_match "${archive}"
-  then
-    # Remove old installs, if they exist and have incorrect md5.
-    if [[ -f "${archive}" ]]
-    then
-      rm -f "${archive}"
-    fi
-  fi
-
-  if curl -L "${url}" -o "${archive}"
-  then
-    true
-  else
-    fail "Failed to download ${url} to ${archive} using 'curl', error code ($?)"
-  fi
-
-  if ! md5_match "$archive"
-  then
-    fail "ERROR:
-
-Archive package downloaded does not match its calculated md5 checksum ${md5}:
-
-  $rvm_archives_path/rvm-${version}.tar.gz
-
-Retry the installation and/or check your networking setup.
-
-Halting installation.
-"
-  fi
-
-  if tar zxf "${archive}" -C "$rvm_src_path/" --no-same-owner
-  then
-    cd "$rvm_src_path/rvm-${version}"
-  else
-    fail "Failed to extract ${archive} to ${rvm_src_path}/,"\
-      "tar command returned error code $?"
-  fi
+  typeset _version
+  _version=$1
+  log "Downloading RVM version ${_version}"
+  get_and_unpack \
+    https://github.com/wayneeseguin/rvm/tarball/${_version} \
+    rvm-${_version}.tar.gz \
+    wayneeseguin-rvm-
 }
 
 install_head()
 {
-  local remote="origin"
+  typeset _repo _branch
+  case "$1" in
+    (/*)
+      _repo=wayneeseguin
+      _branch=${1#/}
+      ;;
+    (*/)
+      _repo=${1%/}
+      _branch=master
+      ;;
+    (*/*)
+      _repo=${1%/*}
+      _branch=${1#*/}
+      ;;
+    (*)
+      _repo=wayneeseguin
+      _branch=$1
+      ;;
+  esac
+  log "Downloading RVM from ${_repo} branch ${_branch}"
+  get_and_unpack \
+    https://github.com/${_repo}/rvm/tarball/${_branch} \
+    ${_repo}-rvm-${_branch}.tgz \
+    ${_repo}-rvm-
+}
 
-  if [[ -d "${rvm_src_path}/rvm/.git" ]]
+get_and_unpack()
+{
+  typeset _url _file _patern
+  _url=$1
+  _file=$2
+  _patern=$3
+
+  if curl -L ${_url} -o ${rvm_archives_path}/${_file}
   then
-    builtin cd "${rvm_src_path}/rvm/"
-
-    if [[ -z "$(git branch | awk "/$branch$/")" ]]
-    then
-      if git checkout -b "$branch" --track "$remote/$branch" 2>/dev/null
-      then
-        log "Successfully checked out branch '$branch'"
-      else
-        fail "$remote $branch remote branch not found."
-      fi
-    elif [[ -z "$(git branch | awk "/\* $branch$/{print \$2}")" ]]
-    then
-      if git checkout $branch 2>/dev/null
-      then
-        log "Successfully checked out branch '$branch'"
-      else
-        fail "Unable to checkout branch $branch."
-      fi
-    fi
-
-    if git pull --rebase $remote $branch
-    then
-      log "Successfully pulled (rebased) from $remote $branch"
-    else
-      fail "Failed pull/rebase $remote $branch"
-    fi
+    true
   else
-    builtin cd "${rvm_src_path}"
-
-    if ! git clone --depth 1 git://github.com/wayneeseguin/rvm.git
-    then
-      if !  git clone https://github.com/wayneeseguin/rvm.git
-      then
-        fail "Unable to clone the RVM repository, attempted both git:// and https://"
-      fi
-    fi
+    typeset ret=$?
+    case $ret in
+      (60)
+        log "
+Could not download '${_url}'.
+  Make sure your certificates are up to date as described above.
+  To continue in insecure mode run 'echo insecure >> ~/.curlrc'.
+"
+        return 60
+        ;;
+      (*)
+        log "
+Could not download '${_url}'.
+  curl returned status '$ret'.
+"
+        return 1
+        ;;
+    esac
   fi
 
-  builtin cd "${rvm_src_path}/rvm/"
+  [[ -d "${rvm_src_path}/rvm" ]] || \mkdir -p "${rvm_src_path}/rvm"
+  if ! builtin cd "${rvm_src_path}/rvm"
+  then
+    log "Could not change directory '${rvm_src_path}/rvm'."
+    return 2
+  fi
 
-  return 0
+  rm -rf ${rvm_src_path}/rvm/*
+  if ! $rvm_tar_command xzf ${rvm_archives_path}/${_file} ${rvm_tar_options:-}
+  then
+    log "Could not extract RVM sources."
+    return 3
+  fi
+
+  if ! mv ${_patern}*/* .
+  then
+    log "Could not move RVM sources path."
+    return 4
+  fi
+  rm -rf ${_patern}*
 }
 
 # Tracing, if asked for.
@@ -184,11 +189,13 @@ then
   do
     if [[ -s "$rvmrc" ]]
     then
-      if \grep '^\s*rvm .*$' "$rvmrc" >/dev/null 2>&1
+      if GREP_OPTIONS="" \grep '^\s*rvm .*$' "$rvmrc" >/dev/null 2>&1
       then
-        printf "\nError: $rvmrc is for rvm settings only.\n"
-        printf "rvm CLI may NOT be called from within $rvmrc. \n"
-        printf "Skipping the loading of $rvmrc\n"
+        printf "%b" "
+Error: $rvmrc is for rvm settings only.
+rvm CLI may NOT be called from within $rvmrc.
+Skipping the loading of $rvmrc
+"
         return 1
       else
         source "$rvmrc"
@@ -208,6 +215,8 @@ then
 fi
 export HOME rvm_path
 
+install_rubies=()
+install_gems=()
 # Parse CLI arguments.
 while (( $# > 0 ))
 do
@@ -230,7 +239,7 @@ do
       fi
       ;;
 
-    --branch) # Install RVM from a given branch
+    --branch|branch) # Install RVM from a given branch
       if [[ -n "${1:-}" ]]
       then
         version="head"
@@ -241,33 +250,48 @@ do
       fi
       ;;
 
-    --user-install)
-      rvm_user_install_flag=1
+    --user-install|--auto)
+      token=${token#--}
+      token=${token//-/_}
+      export "rvm_${token}_flag"=1
+      printf "%b" "Turning on ${token/_/ } mode.\n"
       ;;
 
-    --version)
-      case "$1" in
-        +([[:digit:]]).+([[:digit:]]).+([[:digit:]]))
-          version="$1"
-          shift
-          ;;
-        latest|stable)
-          version="latest"
-          shift
-          ;;
-        head|master)
-          version="head"
-          shift
-          branch="master"
-          ;;
-        *)
-          fail "--version must be followed by a vaild version number x.y.z"
-          ;;
-      esac
+    --version|version)
+      version="$1"
+      shift
       ;;
 
-    +([[:digit:]]).+([[:digit:]]).+([[:digit:]]))
+    head)
+      version="head"
+      branch="master"
+      ;;
+
+    stable|master)
+      version="head"
+      branch="$token"
+      ;;
+
+    latest|latest-*|+([[:digit:]]).+([[:digit:]]).+([[:digit:]]))
       version="$token"
+      ;;
+
+    --ruby)
+      install_rubies+=( ruby )
+      ;;
+
+    --ruby=*)
+      token=${token#--ruby=}
+      install_rubies+=( ${token//,/ } )
+      ;;
+
+    --rails)
+      install_gems+=( rails )
+      ;;
+
+    --gems=*)
+      token=${token#--gems=}
+      install_gems+=( ${token//,/ } )
       ;;
 
     help|usage)
@@ -282,6 +306,34 @@ do
   esac
 done
 
+case "$rvm_path" in
+  *[[:space:]]*)
+      printf "%b" "
+It looks you are one of the happy *space* users(in home dir name),
+RVM is not yet fully ready for it, use this trick to fix it:
+
+    sudo ln -s \"$HOME/.rvm/\" /$USER.rvm
+    echo \"export rvm_path=/$USER.rvm\" >> \"$HOME/.rvmrc\"
+
+and start installing again.
+
+"
+      exit 2
+    ;;
+esac
+
+if (( ${#install_gems[@]} > 0 && ${#install_rubies[@]} == 0 ))
+then
+  install_rubies=( ruby )
+fi
+
+if (( ${#install_rubies[@]} > 0 ))
+then
+  echo "Please read and follow further instructions."
+  echo "Press ENTER to continue."
+  builtin read -n 1 -s -r anykey
+fi
+
 true "${version:=head}"
 
 if [[ "$rvm_path" != /* ]]
@@ -291,7 +343,7 @@ fi
 
 rvm_src_path="$rvm_path/src"
 rvm_archives_path="$rvm_path/archives"
-rvm_releases_url="https://rvm.beginrescueend.com/releases"
+rvm_releases_url="https://rvm.io/releases"
 
 for dir in "$rvm_src_path" "$rvm_archives_path"
 do
@@ -305,37 +357,90 @@ done
 # means was specified, if any. Defaults to head.
 case "${version}" in
   (head)
-    install_head
+    echo "${branch}" > "$rvm_path/RELEASE"
+    install_head ${branch:-master} || exit $?
     ;;
 
   (latest)
-    fetch_version
-    install_release
+    echo "${version}" > "$rvm_path/RELEASE"
+    install_release $(fetch_version "") || exit $?
+    ;;
+
+  (latest-*)
+    echo "${version}" > "$rvm_path/RELEASE"
+    install_release $(fetch_version "${version#latest-}") || exit $?
     ;;
 
   (+([[:digit:]]).+([[:digit:]]).+([[:digit:]])) # x.y.z
-    install_release
+    echo "version" > "$rvm_path/RELEASE"
+    install_release ${version} || exit $?
     ;;
+
   (*)
     fail "Something went wrong, unrecognized version '$version'"
     ;;
 esac
 
-# No matter which one we are doing we install the same way, using the RVM
-#   installer script.
+# No matter which one we are doing we install the same way, using the RVM installer script.
 flags=()
 if (( rvm_trace_flag == 1 ))
-then
-  flags+=("--trace")
+then flags+=("--trace")
 fi
 
 if (( rvm_debug_flag == 1 ))
-then
-  flags+=("--debug")
+then flags+=("--debug")
+fi
+
+if (( rvm_auto_flag == 1 ))
+then flags+=("--auto")
 fi
 
 chmod +x ./scripts/install
-
-# Now we run the RVM installer.
 ./scripts/install ${flags[*]} --path "$rvm_path"
 
+(
+  source ${rvm_scripts_path:-${rvm_path}/scripts}/rvm
+  source ${rvm_scripts_path:-${rvm_path}/scripts}/version
+  __rvm_version
+
+  if (( ${#install_rubies[@]} > 0 ))
+  then
+    {
+      echo "Ruby (and needed base gems) for your selection will be installed shortly."
+      echo "Before it happens, please read and execute the instructions below."
+      echo "Please use a separate terminal to execute any additional commands."
+      echo "Press 'q' to continue."
+    } | less
+  fi
+
+  for _ruby in ${install_rubies[@]}
+  do
+    command rvm install ${_ruby} -j 2
+  done
+  for _ruby in ${install_rubies[@]}
+  do
+    # set the first one as default, skip rest
+    rvm alias create default ${_ruby}
+    break
+  done
+
+  for _gem in ${install_gems[@]}
+  do
+    rvm all do gem install ${_gem}
+  done
+
+  if (( ${#install_rubies[@]} > 0 ))
+  then
+    printf "%b" "
+  * To start using RVM you need to run \`source $rvm_path/scripts/rvm\`
+    in all your open shell windows, in rare cases you need to reopen all shell windows.
+"
+  fi
+
+  if [[ "${install_gems[*]}" =~ "rails" ]]
+  then
+    printf "%b" "
+  * To start using rails you need to run \`rails new <project_dir>\`.
+"
+  fi
+)
